name: Build & Push Multi-arch Docker Images on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [hello-world-nest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.app }} image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg APP_NAME=${{ matrix.app }} \
            -t chathula/${{ matrix.app }}:${{ github.ref_name }} \
            --push \
            -f apps/${{ matrix.app }}/Dockerfile \
            .
