name: Build and Push Docker Images on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [hello-world-nest, another-app]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Nx project ${{ matrix.app }}
        run: npx nx build ${{ matrix.app }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for ${{ matrix.app }}
        run: |
          IMAGE=chathula/${{ matrix.app }}
          TAG=${{ github.ref_name }}
          docker build -t $IMAGE:$TAG --build-arg APP_NAME=${{ matrix.app }} .
          docker push $IMAGE:$TAG
